version: 2.1

# ENV VARS required
# AZURE_SP           - service principal given the Contributor role on the Azure Container Registry
# AZURE_SP_PASSWORD  - service principal password
# AZURE_SP_TENANT    - tenant of servie principal
# AZURE_SUBSCRIPTION - name of Azure subscription with the container registry
# AZURE_ACR_REGISTRY - name of Azure Container Registry

orbs:
  azure-cli: circleci/azure-cli@1.2.0

jobs:
  build-and-deploy-docker-image:
    executor: azure-cli/default
    working_directory: ~/code
    steps:
      - checkout
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - run: az account set --subscription $AZURE_SUBSCRIPTION
      - run: az acr build --registry $AZURE_ACR_REGISTRY --image socketio:$CIRCLE_BRANCH .

workflows:
    build-and-deploy:
      jobs:
        - build-and-deploy-docker-image:
            filters:
              branches:
                only: /^(master|live)$/
